Integration tests (macOS): fix inconsequential ANDROID_SDK_ROOT error
Error: While building Cordova app for platform Android: CordovaError: Failed to find 'ANDROID_SDK_ROOT' environment variable. Try setting it manually.
Solution: Add 'ios' platform instead of 'android' if system is Darwin.